Repository cesium/calendarium, pull requests merged in 2023-05, with the labels that each got.

#109 Add MNOnL event, Update IO & POO event date
  data/events.json
Labels: add activities

#110 LI2 project
  data/events.json
Labels: good first issue, add activities

#111 Clarify Helping Guide
  HELPING_GUIDE.md
Labels: enhancement
