Repository cesium/calendarium, pull requests merged in 2023-03, with the labels that each got.

#81 Add Helping Guide
  HELPING_GUIDE.md
  README.md
Labels: documentation, enhancement

#83 Add PI Evaluations
  data/events.json
Labels: add activities

#84 Improve Schedule Filters & Global Design
  components/CheckBox/checkbox.module.scss
  components/FeedbackForm/feedbackform.module.scss
  components/Navbar/navbar.module.scss
  components/SelectSchedule/SelectSchedule.tsx
  components/SelectSchedule/selectschedule.module.scss
  styles/globals.css
Labels: enhancement

#92 Add 3ʳᵈ year evaluations
  data/events.json
Labels: add activities

#93 Bug Fix on Events Filter
  components/CheckBox/CheckBox.tsx
Labels: bug

#94 Improve UI Coherence
  components/CheckBox/checkbox.module.scss
  components/EventModal/EventModal.tsx
  components/EventModalShift/EventModalShift.tsx
  components/SelectSchedule/selectschedule.module.scss
  package-lock.json
  styles/globals.css
  styles/schedule.module.css
Labels: enhancement

#97 Add Label to Schedule Page
  pages/schedule.tsx
Labels: enhancement

#100 Improve Code Uniformity & Coherence
  components/CheckBox/index.ts
  components/EventFilters/EventFilters.tsx
  components/EventFilters/eventfilters.module.scss
  components/EventFilters/index.ts
  components/EventModalShift/index.ts
  components/FeedbackForm/index.ts
  components/Footer/Footer.tsx
  components/Footer/footer.module.scss
  components/Footer/index.ts
  components/Layout/Layout.tsx
  components/Navbar/Navbar.tsx
  components/Navbar/navbar.module.scss
  components/ScheduleFilters/ScheduleFilters.tsx
  components/ScheduleFilters/index.ts
  components/ScheduleFilters/schedulefilters.module.scss
  components/SelectSchedule/index.ts
  components/ShiftModal/ShiftModal.tsx
  components/ShiftModal/index.ts
  components/Theme/Theme.tsx
  pages/index.tsx
  pages/schedule.tsx
  styles/globals.css
Labels: enhancement

#101 Add Sidebar
  components/EventFilters/EventFilters.tsx
  components/EventFilters/eventfilters.module.scss
  components/Footer/Footer.tsx
  components/Footer/footer.module.scss
  components/Layout/Layout.tsx
  components/Layout/layout.module.scss
  components/Navbar/Navbar.tsx
  components/Navbar/index.ts
  components/Navbar/navbar.module.scss
  components/ScheduleFilters/ScheduleFilters.tsx
  components/ScheduleFilters/schedulefilters.module.scss
  components/Sidebar/Sidebar.tsx
  components/Sidebar/index.ts
  components/Sidebar/sidebar.module.scss
  package-lock.json
  pages/index.tsx
  pages/schedule.tsx
  styles/Home.module.css
  styles/schedule.module.css
  tailwind.config.js
Labels: enhancement

#104 Fix server side timezone
  README.md
  netlify.toml
  package-lock.json
  package.json
  pages/index.tsx
Labels: bug
