Repository cesium/calendarium, pull requests merged in 2023-09, with the labels that each got.

#125 Add Color Themes
  README.md
  components/EventFilters/EventFilters.tsx
  components/EventModal/EventModal.tsx
  components/Layout/Layout.tsx
  components/Notifications/Notifications.tsx
  components/ScheduleFilters/ScheduleFilters.tsx
  components/Settings/Settings.tsx
  components/Settings/index.ts
  components/ShiftModal/ShiftModal.tsx
  components/Sidebar/Sidebar.tsx
  components/Sidebar/sidebar.module.scss
  data/notifications.json
  package-lock.json
  package.json
  pages/index.tsx
  pages/schedule.tsx
  styles/globals.css
  tailwind.config.js
  utils/utils.tsx
Labels: enhancement

#127 feat: update shifts
  data/filters.json
  data/shifts.json
  scraper/modules/create_filters.py
Labels: add activities

#126 Export to Calendar (URL)
  .env.development
  .env.production
  README.md
  components/ActiveLink/ActiveLink.tsx
  components/CalendarExportModal/CalendarExportModal.tsx
  components/CalendarExportModal/index.ts
  components/ClearScheduleButton/ClearScheduleButton.tsx
  components/ClearScheduleButton/index.ts
  components/ExportButton/ExportButton.tsx
  components/ExportButton/index.ts
  components/Layout/Layout.tsx
  components/Sidebar/Sidebar.tsx
  data/notifications.json
  netlify.toml
  package-lock.json
  package.json
  pages/api/export/events.tsx
  pages/api/export/schedule.tsx
  pages/index.tsx
  pages/schedule.tsx
Labels: enhancement

#128 Improve Notifications
  components/Notifications/Notifications.tsx
  data/notifications.json
  tailwind.config.js
Labels: enhancement

#130 Change schedule time gutter from 12h to 24h format
  pages/index.tsx
  pages/schedule.tsx
Labels: enhancement

#138 bug: duplicated filters
  data/filters.json
Labels: bug

#137 Improve SEO
  components/CalendarExportModal/CalendarExportModal.tsx
  components/ExportButton/ExportButton.tsx
  components/Layout/Layout.tsx
  components/Layout/layout.module.scss
  components/Notifications/Notifications.tsx
  components/Sidebar/Sidebar.tsx
  components/Sidebar/sidebar.module.scss
  pages/index.tsx
  pages/schedule.tsx
Labels: enhancement

#136 Add 3y-1sem Events
  data/events.json
  data/notifications.json
Labels: add activities

#139 feat: update shifts
  data/shifts.json
Labels: add activities

#141 bug fix: duplicated filter name
  data/filters.json
Labels: bug

#135 Refactor Event & Schedule Filters
  components/EventFilters/EventFilters.tsx
  components/EventFilters/eventfilters.module.scss
  components/FilterBlock/FilterBlock.tsx
  components/FilterBlock/index.ts
  components/ScheduleFilters/ScheduleFilters.tsx
  components/ScheduleFilters/schedulefilters.module.scss
  components/Settings/Settings.tsx
  components/Themes/Themes.tsx
  components/Themes/index.tsx
  pages/index.tsx
  pages/schedule.tsx
  tailwind.config.js
  types/index.ts
  utils/index.ts
Labels: enhancement

#140 General Improvements
  components/Layout/Layout.tsx
  components/Layout/layout.module.scss
  pages/index.tsx
  pages/schedule.tsx
  styles/events.module.css
Labels: enhancement

#143 Preventing UCs with same IDs to be duplicated
  scraper/modules/subjects_scraper.py
Labels: bug

#144 fix: events display neutral color
  pages/index.tsx
  pages/schedule.tsx
Labels: bug

#142 Use Google Sheets as database for events
  .env.development
  .env.local.sample
  .env.production
  .gitignore
  data/events.json
  netlify.toml
  package-lock.json
  package.json
  pages/index.tsx
Labels: enhancement

#146 Warning User for repeated short names
  scraper/modules/subjects_scraper.py
Labels: enhancement

#147 Fix Events API
  pages/api/export/events.tsx
Labels: bug

#148 Update Shifts
  data/filters.json
  data/shifts.json
  scraper/.gitignore
Labels: add activities

#149 fix: daylight savings
  .nvmrc
  netlify.toml
  pages/index.tsx
Labels: bug
